http://localhost:3001

###
GET http://localhost:3001/api/users/62549c2af25b97d7459f7aa6
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmaXJzdE5hbWUiOiJEZWJvcmFoIiwibGFzdE5hbWUiOiJNZW5hIElJSSIsImhhbmRsZSI6IkBkZWJvcmFoZG9lIiwiZW1haWwiOiJkZWJvcmFoQGVtYWlsLmNvbSIsInBpYyI6Imh0dHBzOi8vcmFuZG9tdXNlci5tZS9hcGkvcG9ydHJhaXRzL3dvbWVuLzIuanBnIiwiaWQiOjIsImlhdCI6MTY0OTE3MDQxMH0.PS09DR-a2KQcn5POWy7dXjZy9VkS8FtL-OGlLL5mzCU

###
GET http://localhost:3001/api/users/search/p
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmaXJzdE5hbWUiOiJEZWJvcmFoIiwibGFzdE5hbWUiOiJNZW5hIElJSSIsImhhbmRsZSI6IkBkZWJvcmFoZG9lIiwiZW1haWwiOiJkZWJvcmFoQGVtYWlsLmNvbSIsInBpYyI6Imh0dHBzOi8vcmFuZG9tdXNlci5tZS9hcGkvcG9ydHJhaXRzL3dvbWVuLzIuanBnIiwiaWQiOjIsImlhdCI6MTY0OTE3MDQxMH0.PS09DR-a2KQcn5POWy7dXjZy9VkS8FtL-OGlLL5mzCU

###
DELETE  http://localhost:3001/api/users/625e1bbba93e0413601ef8a5
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmaXJzdE5hbWUiOiJEZWJvcmFoIiwibGFzdE5hbWUiOiJNZW5hIElJSSIsImhhbmRsZSI6IkBkZWJvcmFoZG9lIiwiZW1haWwiOiJkZWJvcmFoQGVtYWlsLmNvbSIsInBpYyI6Imh0dHBzOi8vcmFuZG9tdXNlci5tZS9hcGkvcG9ydHJhaXRzL3dvbWVuLzIuanBnIiwiaWQiOjIsImlhdCI6MTY0OTE3MDQxMH0.PS09DR-a2KQcn5POWy7dXjZy9VkS8FtL-OGlLL5mzCU

###
GET http://localhost:3001/api/users/handle/@deborahdoe
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmaXJzdE5hbWUiOiJKb2FubmEiLCJsYXN0TmFtZSI6IkRvZSIsImhhbmRsZSI6IkBqb2FubmFkb2UiLCJlbWFpbCI6IkpvYW5uYUBlbWFpbC5jb20iLCJwaWMiOiJodHRwczovL3JhbmRvbXVzZXIubWUvYXBpL3BvcnRyYWl0cy93b21lbi8yLmpwZyIsImlkIjoyLCJpYXQiOjE2NDkwOTg1NDd9.ZvLgeTWWJNYsUK_tOXMge77JB8HT9LX6Ajk_43pCWaM


###
POST http://localhost:3001/api/users
Content-Type: application/json

{
  "firstName": "Andres",
  "lastName": "Mena",
  "handle": "@andresmena",
  "password": "password",
  "email": "andres@email.com",
  "pic": "https://randomuser.me/api/portraits/men/4.jpg"
}

###
PATCH  http://localhost:3001/api/users/62549c2af25b97d7459f7aa6
Content-Type: application/json

{
  "password": "password"
}

###
POST http://localhost:3001/api/users/login
Content-Type: application/json

{
  "email": "deborah@email.com",
  "password": "password"
}

###
POST http://localhost:3001/api/users/seed