GET http://localhost:3001/api/tasks
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmaXJzdE5hbWUiOiJEZWJvcmFoIiwibGFzdE5hbWUiOiJNZW5hIElJSSIsImhhbmRsZSI6IkBkZWJvcmFoZG9lIiwiZW1haWwiOiJkZWJvcmFoQGVtYWlsLmNvbSIsInBpYyI6Imh0dHBzOi8vcmFuZG9tdXNlci5tZS9hcGkvcG9ydHJhaXRzL3dvbWVuLzIuanBnIiwiaWQiOjIsImlhdCI6MTY0OTE3MDQxMH0.PS09DR-a2KQcn5POWy7dXjZy9VkS8FtL-OGlLL5mzCU

###
GET http://localhost:3001/api/tasks/62507fb1bf3fd6943b6521a4
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmaXJzdE5hbWUiOiJEZWJvcmFoIiwibGFzdE5hbWUiOiJNZW5hIElJSSIsImhhbmRsZSI6IkBkZWJvcmFoZG9lIiwiZW1haWwiOiJkZWJvcmFoQGVtYWlsLmNvbSIsInBpYyI6Imh0dHBzOi8vcmFuZG9tdXNlci5tZS9hcGkvcG9ydHJhaXRzL3dvbWVuLzIuanBnIiwiaWQiOjIsImlhdCI6MTY0OTE3MDQxMH0.PS09DR-a2KQcn5POWy7dXjZy9VkS8FtL-OGlLL5mzCU

###
GET http://localhost:3001/api/tasks/mytasks/@deborahdoe
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmaXJzdE5hbWUiOiJEZWJvcmFoIiwibGFzdE5hbWUiOiJNZW5hIElJSSIsImhhbmRsZSI6IkBkZWJvcmFoZG9lIiwiZW1haWwiOiJkZWJvcmFoQGVtYWlsLmNvbSIsInBpYyI6Imh0dHBzOi8vcmFuZG9tdXNlci5tZS9hcGkvcG9ydHJhaXRzL3dvbWVuLzIuanBnIiwiaWQiOjIsImlhdCI6MTY0OTE3MDQxMH0.PS09DR-a2KQcn5POWy7dXjZy9VkS8FtL-OGlLL5mzCU

###
DELETE http://localhost:3001/api/tasks/1
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmaXJzdE5hbWUiOiJEZWJvcmFoIiwibGFzdE5hbWUiOiJNZW5hIElJSSIsImhhbmRsZSI6IkBkZWJvcmFoZG9lIiwiZW1haWwiOiJkZWJvcmFoQGVtYWlsLmNvbSIsInBpYyI6Imh0dHBzOi8vcmFuZG9tdXNlci5tZS9hcGkvcG9ydHJhaXRzL3dvbWVuLzIuanBnIiwiaWQiOjIsImlhdCI6MTY0OTE3MDQxMH0.PS09DR-a2KQcn5POWy7dXjZy9VkS8FtL-OGlLL5mzCU


###
POST http://localhost:3001/api/tasks
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmaXJzdE5hbWUiOiJEZWJvcmFoIiwibGFzdE5hbWUiOiJNZW5hIElJSSIsImhhbmRsZSI6IkBkZWJvcmFoZG9lIiwiZW1haWwiOiJkZWJvcmFoQGVtYWlsLmNvbSIsInBpYyI6Imh0dHBzOi8vcmFuZG9tdXNlci5tZS9hcGkvcG9ydHJhaXRzL3dvbWVuLzIuanBnIiwiaWQiOjIsImlhdCI6MTY0OTE3MDQxMH0.PS09DR-a2KQcn5POWy7dXjZy9VkS8FtL-OGlLL5mzCU


{
  "task": "server test task",
    "dueDate": "2022-4-10",
    "creator": "@andresmena",
    "taskee": "@johndoe"
}

###
PATCH http://localhost:3001/api/tasks/2
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmaXJzdE5hbWUiOiJEZWJvcmFoIiwibGFzdE5hbWUiOiJNZW5hIElJSSIsImhhbmRsZSI6IkBkZWJvcmFoZG9lIiwiZW1haWwiOiJkZWJvcmFoQGVtYWlsLmNvbSIsInBpYyI6Imh0dHBzOi8vcmFuZG9tdXNlci5tZS9hcGkvcG9ydHJhaXRzL3dvbWVuLzIuanBnIiwiaWQiOjIsImlhdCI6MTY0OTE3MDQxMH0.PS09DR-a2KQcn5POWy7dXjZy9VkS8FtL-OGlLL5mzCU


{
    "creator": "@andresmena"
}

###
POST http://localhost:3001/api/tasks/seed
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmaXJzdE5hbWUiOiJEZWJvcmFoIiwibGFzdE5hbWUiOiJNZW5hIElJSSIsImhhbmRsZSI6IkBkZWJvcmFoZG9lIiwiZW1haWwiOiJkZWJvcmFoQGVtYWlsLmNvbSIsInBpYyI6Imh0dHBzOi8vcmFuZG9tdXNlci5tZS9hcGkvcG9ydHJhaXRzL3dvbWVuLzIuanBnIiwiaWQiOjIsImlhdCI6MTY0OTE3MDQxMH0.PS09DR-a2KQcn5POWy7dXjZy9VkS8FtL-OGlLL5mzCU
